### ISSUE TITLE
Word Embeddings in Data Preprocessing

### ISSUE THREAD

**Issue by RoiOng** [iamRusty/Sentiment-Analysis-of-Filipino-Tweets#3]
Hello! Are you familiar with word embeddings? I would just like to ask about the conversion of the Filipino dataset from words to vectors that are used as inputs. Do you suggest the use of word embedding model such as word2vec, fastext, and glove? Or is it better to use the embedding layer function in keras?

**Comment by iamRusty** [comment]
I haven't implemented those algorithm yet however their results look promising.

**Comment by RoiOng** [comment]
Thank you for your response
